// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message_processor.proto

package message_processor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PROCESSOR struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	NumberCores          uint32   `protobuf:"varint,3,opt,name=number_cores,json=numberCores,proto3" json:"number_cores,omitempty"`
	NumberThread         uint32   `protobuf:"varint,4,opt,name=number_thread,json=numberThread,proto3" json:"number_thread,omitempty"`
	MinGz                float64  `protobuf:"fixed64,5,opt,name=min_gz,json=minGz,proto3" json:"min_gz,omitempty"`
	MaxGz                float64  `protobuf:"fixed64,6,opt,name=max_gz,json=maxGz,proto3" json:"max_gz,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PROCESSOR) Reset()         { *m = PROCESSOR{} }
func (m *PROCESSOR) String() string { return proto.CompactTextString(m) }
func (*PROCESSOR) ProtoMessage()    {}
func (*PROCESSOR) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfed2ca2b5430aca, []int{0}
}

func (m *PROCESSOR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PROCESSOR.Unmarshal(m, b)
}
func (m *PROCESSOR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PROCESSOR.Marshal(b, m, deterministic)
}
func (m *PROCESSOR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PROCESSOR.Merge(m, src)
}
func (m *PROCESSOR) XXX_Size() int {
	return xxx_messageInfo_PROCESSOR.Size(m)
}
func (m *PROCESSOR) XXX_DiscardUnknown() {
	xxx_messageInfo_PROCESSOR.DiscardUnknown(m)
}

var xxx_messageInfo_PROCESSOR proto.InternalMessageInfo

func (m *PROCESSOR) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PROCESSOR) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PROCESSOR) GetNumberCores() uint32 {
	if m != nil {
		return m.NumberCores
	}
	return 0
}

func (m *PROCESSOR) GetNumberThread() uint32 {
	if m != nil {
		return m.NumberThread
	}
	return 0
}

func (m *PROCESSOR) GetMinGz() float64 {
	if m != nil {
		return m.MinGz
	}
	return 0
}

func (m *PROCESSOR) GetMaxGz() float64 {
	if m != nil {
		return m.MaxGz
	}
	return 0
}

type GPU struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	MinGz                float64  `protobuf:"fixed64,3,opt,name=min_gz,json=minGz,proto3" json:"min_gz,omitempty"`
	MaxGz                float64  `protobuf:"fixed64,4,opt,name=max_gz,json=maxGz,proto3" json:"max_gz,omitempty"`
	Memory               *Memory  `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPU) Reset()         { *m = GPU{} }
func (m *GPU) String() string { return proto.CompactTextString(m) }
func (*GPU) ProtoMessage()    {}
func (*GPU) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfed2ca2b5430aca, []int{1}
}

func (m *GPU) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPU.Unmarshal(m, b)
}
func (m *GPU) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPU.Marshal(b, m, deterministic)
}
func (m *GPU) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPU.Merge(m, src)
}
func (m *GPU) XXX_Size() int {
	return xxx_messageInfo_GPU.Size(m)
}
func (m *GPU) XXX_DiscardUnknown() {
	xxx_messageInfo_GPU.DiscardUnknown(m)
}

var xxx_messageInfo_GPU proto.InternalMessageInfo

func (m *GPU) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GPU) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *GPU) GetMinGz() float64 {
	if m != nil {
		return m.MinGz
	}
	return 0
}

func (m *GPU) GetMaxGz() float64 {
	if m != nil {
		return m.MaxGz
	}
	return 0
}

func (m *GPU) GetMemory() *Memory {
	if m != nil {
		return m.Memory
	}
	return nil
}

func init() {
	proto.RegisterType((*PROCESSOR)(nil), "PROCESSOR")
	proto.RegisterType((*GPU)(nil), "GPU")
}

func init() {
	proto.RegisterFile("message_processor.proto", fileDescriptor_cfed2ca2b5430aca)
}

var fileDescriptor_cfed2ca2b5430aca = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xcf, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x8d, 0x2f, 0x28, 0xca, 0x4f, 0x06, 0x32, 0xf3, 0x8b, 0xf4, 0x80, 0xac, 0x92,
	0x7c, 0x29, 0x9e, 0xdc, 0xd4, 0xdc, 0xfc, 0xa2, 0x4a, 0x08, 0x4f, 0x69, 0x3d, 0x23, 0x17, 0x67,
	0x40, 0x90, 0xbf, 0xb3, 0x6b, 0x70, 0xb0, 0x7f, 0x90, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e,
	0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x2d, 0x24, 0xc1, 0xc5, 0x9e, 0x98, 0x92,
	0x52, 0x04, 0x34, 0x42, 0x82, 0x09, 0x2c, 0x0c, 0xe3, 0x0a, 0x29, 0x72, 0xf1, 0xe4, 0x95, 0xe6,
	0x26, 0xa5, 0x16, 0xc5, 0x27, 0xe7, 0x03, 0x05, 0x24, 0x98, 0x81, 0xd2, 0xbc, 0x41, 0xdc, 0x10,
	0x31, 0x67, 0x90, 0x90, 0x90, 0x32, 0x17, 0x2f, 0x54, 0x49, 0x49, 0x46, 0x51, 0x6a, 0x62, 0x8a,
	0x04, 0x0b, 0x58, 0x0d, 0x54, 0x5f, 0x08, 0x58, 0x4c, 0x48, 0x94, 0x8b, 0x2d, 0x37, 0x33, 0x2f,
	0x3e, 0xbd, 0x4a, 0x82, 0x15, 0x28, 0xcb, 0x18, 0xc4, 0x0a, 0xe4, 0xb9, 0x57, 0x81, 0x85, 0x13,
	0x2b, 0x40, 0xc2, 0x6c, 0x50, 0xe1, 0xc4, 0x0a, 0xf7, 0x2a, 0xa5, 0x3a, 0x2e, 0x66, 0xf7, 0x80,
	0x50, 0xac, 0x4e, 0x15, 0xe1, 0x62, 0x4d, 0x2a, 0x4a, 0xcc, 0x4b, 0x81, 0x3a, 0x14, 0xc2, 0x41,
	0x32, 0x9e, 0x19, 0xbb, 0xf1, 0x2c, 0x48, 0xc6, 0x0b, 0xc9, 0x03, 0x85, 0xc1, 0x01, 0x04, 0x76,
	0x0c, 0xb7, 0x11, 0xbb, 0x9e, 0x2f, 0x98, 0x1b, 0x04, 0x15, 0x4e, 0x62, 0x03, 0x07, 0x9c, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x98, 0xdb, 0xe7, 0xf8, 0x61, 0x01, 0x00, 0x00,
}
