// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package server

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Store struct {
	S                    string   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Store) Reset()         { *m = Store{} }
func (m *Store) String() string { return proto.CompactTextString(m) }
func (*Store) ProtoMessage()    {}
func (*Store) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *Store) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Store.Unmarshal(m, b)
}
func (m *Store) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Store.Marshal(b, m, deterministic)
}
func (m *Store) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Store.Merge(m, src)
}
func (m *Store) XXX_Size() int {
	return xxx_messageInfo_Store.Size(m)
}
func (m *Store) XXX_DiscardUnknown() {
	xxx_messageInfo_Store.DiscardUnknown(m)
}

var xxx_messageInfo_Store proto.InternalMessageInfo

func (m *Store) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func init() {
	proto.RegisterType((*Store)(nil), "Store")
}

func init() {
	proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7)
}

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 89 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x12, 0xe5, 0x62, 0x0d, 0x2e, 0xc9, 0x2f,
	0x4a, 0x15, 0xe2, 0xe1, 0x62, 0x2c, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x2c, 0x36,
	0x52, 0xe4, 0x62, 0x77, 0x4f, 0x2d, 0xf1, 0x2c, 0x49, 0xcd, 0x15, 0x12, 0xe3, 0x62, 0x01, 0xd3,
	0x6c, 0x7a, 0x60, 0x85, 0x52, 0x50, 0x3a, 0x89, 0x0d, 0x6c, 0x80, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x7d, 0xc3, 0xb5, 0xbc, 0x50, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GetItemClient is the client API for GetItem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetItemClient interface {
	Item(ctx context.Context, in *Store, opts ...grpc.CallOption) (*Store, error)
}

type getItemClient struct {
	cc grpc.ClientConnInterface
}

func NewGetItemClient(cc grpc.ClientConnInterface) GetItemClient {
	return &getItemClient{cc}
}

func (c *getItemClient) Item(ctx context.Context, in *Store, opts ...grpc.CallOption) (*Store, error) {
	out := new(Store)
	err := c.cc.Invoke(ctx, "/GetItem/Item", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetItemServer is the server API for GetItem service.
type GetItemServer interface {
	Item(context.Context, *Store) (*Store, error)
}

// UnimplementedGetItemServer can be embedded to have forward compatible implementations.
type UnimplementedGetItemServer struct {
}

func (*UnimplementedGetItemServer) Item(ctx context.Context, req *Store) (*Store, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Item not implemented")
}

func RegisterGetItemServer(s *grpc.Server, srv GetItemServer) {
	s.RegisterService(&_GetItem_serviceDesc, srv)
}

func _GetItem_Item_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Store)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetItemServer).Item(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GetItem/Item",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetItemServer).Item(ctx, req.(*Store))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetItem_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GetItem",
	HandlerType: (*GetItemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Item",
			Handler:    _GetItem_Item_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
